version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION ##this is the elk version declared in .env
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /usr/share/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g -Dlog4j2.formatMsgNoLookups=True" ##this sets the memory for elasticsearch, we can also set java variables .. larger chunk since the work is done here...
      ELASTIC_PASSWORD: changeme ##this is a default, so probably a good call to change it
    networks:
      - elk
    restart: unless-stopped ##persist if server shuts down

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m" ##this sets the memory for logstash, we can also include java options
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped ##persist if server shuts down

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped ##persist if server shuts down

networks:

  elk:
    driver: bridge
